// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manage.proto

package manage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TypeQuery int32

const (
	TypeQuery_DETAIL  TypeQuery = 0
	TypeQuery_SUMMARY TypeQuery = 1
	TypeQuery_UNKNOWN TypeQuery = 2
)

var TypeQuery_name = map[int32]string{
	0: "DETAIL",
	1: "SUMMARY",
	2: "UNKNOWN",
}

var TypeQuery_value = map[string]int32{
	"DETAIL":  0,
	"SUMMARY": 1,
	"UNKNOWN": 2,
}

func (x TypeQuery) String() string {
	return proto.EnumName(TypeQuery_name, int32(x))
}

func (TypeQuery) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{0}
}

type ResponseWideType int32

const (
	ResponseWide_EMPTY  ResponseWideType = 0
	ResponseWide_FINISH ResponseWideType = 1
	ResponseWide_CREATE ResponseWideType = 2
	ResponseWide_ANSWER ResponseWideType = 3
)

var ResponseWideType_name = map[int32]string{
	0: "EMPTY",
	1: "FINISH",
	2: "CREATE",
	3: "ANSWER",
}

var ResponseWideType_value = map[string]int32{
	"EMPTY":  0,
	"FINISH": 1,
	"CREATE": 2,
	"ANSWER": 3,
}

func (x ResponseWideType) String() string {
	return proto.EnumName(ResponseWideType_name, int32(x))
}

func (ResponseWideType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{3, 0}
}

type StorageSide int32

const (
	Storage_IN  StorageSide = 0
	Storage_OUT StorageSide = 1
)

var StorageSide_name = map[int32]string{
	0: "IN",
	1: "OUT",
}

var StorageSide_value = map[string]int32{
	"IN":  0,
	"OUT": 1,
}

func (x StorageSide) String() string {
	return proto.EnumName(StorageSide_name, int32(x))
}

func (StorageSide) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{15, 0}
}

type TypeServerSide int32

const (
	TypeServer_IN  TypeServerSide = 0
	TypeServer_OUT TypeServerSide = 1
)

var TypeServerSide_name = map[int32]string{
	0: "IN",
	1: "OUT",
}

var TypeServerSide_value = map[string]int32{
	"IN":  0,
	"OUT": 1,
}

func (x TypeServerSide) String() string {
	return proto.EnumName(TypeServerSide_name, int32(x))
}

func (TypeServerSide) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{19, 0}
}

type Request struct {
	Key                  uint32   `protobuf:"varint,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Request) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response struct {
	Key                  uint32   `protobuf:"varint,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type EXTRA struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	PollId               int64    `protobuf:"varint,2,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EXTRA) Reset()         { *m = EXTRA{} }
func (m *EXTRA) String() string { return proto.CompactTextString(m) }
func (*EXTRA) ProtoMessage()    {}
func (*EXTRA) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{2}
}

func (m *EXTRA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EXTRA.Unmarshal(m, b)
}
func (m *EXTRA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EXTRA.Marshal(b, m, deterministic)
}
func (m *EXTRA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EXTRA.Merge(m, src)
}
func (m *EXTRA) XXX_Size() int {
	return xxx_messageInfo_EXTRA.Size(m)
}
func (m *EXTRA) XXX_DiscardUnknown() {
	xxx_messageInfo_EXTRA.DiscardUnknown(m)
}

var xxx_messageInfo_EXTRA proto.InternalMessageInfo

func (m *EXTRA) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EXTRA) GetPollId() int64 {
	if m != nil {
		return m.PollId
	}
	return 0
}

func (m *EXTRA) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type ResponseWide struct {
	Type                 ResponseWideType `protobuf:"varint,1,opt,name=Type,proto3,enum=manage.ResponseWideType" json:"Type,omitempty"`
	Key                  uint32           `protobuf:"varint,2,opt,name=Key,proto3" json:"Key,omitempty"`
	IdPoll               int64            `protobuf:"varint,3,opt,name=IdPoll,proto3" json:"IdPoll,omitempty"`
	Data                 []byte           `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResponseWide) Reset()         { *m = ResponseWide{} }
func (m *ResponseWide) String() string { return proto.CompactTextString(m) }
func (*ResponseWide) ProtoMessage()    {}
func (*ResponseWide) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{3}
}

func (m *ResponseWide) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseWide.Unmarshal(m, b)
}
func (m *ResponseWide) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseWide.Marshal(b, m, deterministic)
}
func (m *ResponseWide) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseWide.Merge(m, src)
}
func (m *ResponseWide) XXX_Size() int {
	return xxx_messageInfo_ResponseWide.Size(m)
}
func (m *ResponseWide) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseWide.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseWide proto.InternalMessageInfo

func (m *ResponseWide) GetType() ResponseWideType {
	if m != nil {
		return m.Type
	}
	return ResponseWide_EMPTY
}

func (m *ResponseWide) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *ResponseWide) GetIdPoll() int64 {
	if m != nil {
		return m.IdPoll
	}
	return 0
}

func (m *ResponseWide) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type COUNTS_VARIANT struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Free                 bool     `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *COUNTS_VARIANT) Reset()         { *m = COUNTS_VARIANT{} }
func (m *COUNTS_VARIANT) String() string { return proto.CompactTextString(m) }
func (*COUNTS_VARIANT) ProtoMessage()    {}
func (*COUNTS_VARIANT) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{4}
}

func (m *COUNTS_VARIANT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_COUNTS_VARIANT.Unmarshal(m, b)
}
func (m *COUNTS_VARIANT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_COUNTS_VARIANT.Marshal(b, m, deterministic)
}
func (m *COUNTS_VARIANT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_COUNTS_VARIANT.Merge(m, src)
}
func (m *COUNTS_VARIANT) XXX_Size() int {
	return xxx_messageInfo_COUNTS_VARIANT.Size(m)
}
func (m *COUNTS_VARIANT) XXX_DiscardUnknown() {
	xxx_messageInfo_COUNTS_VARIANT.DiscardUnknown(m)
}

var xxx_messageInfo_COUNTS_VARIANT proto.InternalMessageInfo

func (m *COUNTS_VARIANT) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *COUNTS_VARIANT) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *COUNTS_VARIANT) GetFree() bool {
	if m != nil {
		return m.Free
	}
	return false
}

type TEXTS_VARIANT struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash                 [][]byte `protobuf:"bytes,2,rep,name=hash,proto3" json:"hash,omitempty"`
	Text                 []string `protobuf:"bytes,3,rep,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TEXTS_VARIANT) Reset()         { *m = TEXTS_VARIANT{} }
func (m *TEXTS_VARIANT) String() string { return proto.CompactTextString(m) }
func (*TEXTS_VARIANT) ProtoMessage()    {}
func (*TEXTS_VARIANT) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{5}
}

func (m *TEXTS_VARIANT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TEXTS_VARIANT.Unmarshal(m, b)
}
func (m *TEXTS_VARIANT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TEXTS_VARIANT.Marshal(b, m, deterministic)
}
func (m *TEXTS_VARIANT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TEXTS_VARIANT.Merge(m, src)
}
func (m *TEXTS_VARIANT) XXX_Size() int {
	return xxx_messageInfo_TEXTS_VARIANT.Size(m)
}
func (m *TEXTS_VARIANT) XXX_DiscardUnknown() {
	xxx_messageInfo_TEXTS_VARIANT.DiscardUnknown(m)
}

var xxx_messageInfo_TEXTS_VARIANT proto.InternalMessageInfo

func (m *TEXTS_VARIANT) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TEXTS_VARIANT) GetHash() [][]byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *TEXTS_VARIANT) GetText() []string {
	if m != nil {
		return m.Text
	}
	return nil
}

type SummaryAnswersCounts struct {
	AnswersId            []*COUNTS_VARIANT `protobuf:"bytes,1,rep,name=answers_id,json=answersId,proto3" json:"answers_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SummaryAnswersCounts) Reset()         { *m = SummaryAnswersCounts{} }
func (m *SummaryAnswersCounts) String() string { return proto.CompactTextString(m) }
func (*SummaryAnswersCounts) ProtoMessage()    {}
func (*SummaryAnswersCounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{6}
}

func (m *SummaryAnswersCounts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummaryAnswersCounts.Unmarshal(m, b)
}
func (m *SummaryAnswersCounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummaryAnswersCounts.Marshal(b, m, deterministic)
}
func (m *SummaryAnswersCounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummaryAnswersCounts.Merge(m, src)
}
func (m *SummaryAnswersCounts) XXX_Size() int {
	return xxx_messageInfo_SummaryAnswersCounts.Size(m)
}
func (m *SummaryAnswersCounts) XXX_DiscardUnknown() {
	xxx_messageInfo_SummaryAnswersCounts.DiscardUnknown(m)
}

var xxx_messageInfo_SummaryAnswersCounts proto.InternalMessageInfo

func (m *SummaryAnswersCounts) GetAnswersId() []*COUNTS_VARIANT {
	if m != nil {
		return m.AnswersId
	}
	return nil
}

type SummaryAnswersTexts struct {
	AnswerstextHash      [][]byte         `protobuf:"bytes,1,rep,name=answerstext_hash,json=answerstextHash,proto3" json:"answerstext_hash,omitempty"`
	AnswersId            []*TEXTS_VARIANT `protobuf:"bytes,2,rep,name=answers_id,json=answersId,proto3" json:"answers_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SummaryAnswersTexts) Reset()         { *m = SummaryAnswersTexts{} }
func (m *SummaryAnswersTexts) String() string { return proto.CompactTextString(m) }
func (*SummaryAnswersTexts) ProtoMessage()    {}
func (*SummaryAnswersTexts) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{7}
}

func (m *SummaryAnswersTexts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummaryAnswersTexts.Unmarshal(m, b)
}
func (m *SummaryAnswersTexts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummaryAnswersTexts.Marshal(b, m, deterministic)
}
func (m *SummaryAnswersTexts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummaryAnswersTexts.Merge(m, src)
}
func (m *SummaryAnswersTexts) XXX_Size() int {
	return xxx_messageInfo_SummaryAnswersTexts.Size(m)
}
func (m *SummaryAnswersTexts) XXX_DiscardUnknown() {
	xxx_messageInfo_SummaryAnswersTexts.DiscardUnknown(m)
}

var xxx_messageInfo_SummaryAnswersTexts proto.InternalMessageInfo

func (m *SummaryAnswersTexts) GetAnswerstextHash() [][]byte {
	if m != nil {
		return m.AnswerstextHash
	}
	return nil
}

func (m *SummaryAnswersTexts) GetAnswersId() []*TEXTS_VARIANT {
	if m != nil {
		return m.AnswersId
	}
	return nil
}

type VARIANTS struct {
	QuestionId           int64             `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswersId            []*COUNTS_VARIANT `protobuf:"bytes,2,rep,name=answers_id,json=answersId,proto3" json:"answers_id,omitempty"`
	AnswerText           []string          `protobuf:"bytes,3,rep,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	FreeText             []*TEXTS_VARIANT  `protobuf:"bytes,4,rep,name=free_text,json=freeText,proto3" json:"free_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VARIANTS) Reset()         { *m = VARIANTS{} }
func (m *VARIANTS) String() string { return proto.CompactTextString(m) }
func (*VARIANTS) ProtoMessage()    {}
func (*VARIANTS) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{8}
}

func (m *VARIANTS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VARIANTS.Unmarshal(m, b)
}
func (m *VARIANTS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VARIANTS.Marshal(b, m, deterministic)
}
func (m *VARIANTS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VARIANTS.Merge(m, src)
}
func (m *VARIANTS) XXX_Size() int {
	return xxx_messageInfo_VARIANTS.Size(m)
}
func (m *VARIANTS) XXX_DiscardUnknown() {
	xxx_messageInfo_VARIANTS.DiscardUnknown(m)
}

var xxx_messageInfo_VARIANTS proto.InternalMessageInfo

func (m *VARIANTS) GetQuestionId() int64 {
	if m != nil {
		return m.QuestionId
	}
	return 0
}

func (m *VARIANTS) GetAnswersId() []*COUNTS_VARIANT {
	if m != nil {
		return m.AnswersId
	}
	return nil
}

func (m *VARIANTS) GetAnswerText() []string {
	if m != nil {
		return m.AnswerText
	}
	return nil
}

func (m *VARIANTS) GetFreeText() []*TEXTS_VARIANT {
	if m != nil {
		return m.FreeText
	}
	return nil
}

type Items struct {
	Type                 string      `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	PollId               int64       `protobuf:"varint,2,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Items                []*VARIANTS `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Limitvote            int32       `protobuf:"varint,4,opt,name=limitvote,proto3" json:"limitvote,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Items) Reset()         { *m = Items{} }
func (m *Items) String() string { return proto.CompactTextString(m) }
func (*Items) ProtoMessage()    {}
func (*Items) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{9}
}

func (m *Items) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Items.Unmarshal(m, b)
}
func (m *Items) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Items.Marshal(b, m, deterministic)
}
func (m *Items) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Items.Merge(m, src)
}
func (m *Items) XXX_Size() int {
	return xxx_messageInfo_Items.Size(m)
}
func (m *Items) XXX_DiscardUnknown() {
	xxx_messageInfo_Items.DiscardUnknown(m)
}

var xxx_messageInfo_Items proto.InternalMessageInfo

func (m *Items) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Items) GetPollId() int64 {
	if m != nil {
		return m.PollId
	}
	return 0
}

func (m *Items) GetItems() []*VARIANTS {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Items) GetLimitvote() int32 {
	if m != nil {
		return m.Limitvote
	}
	return 0
}

type PAYLOAD struct {
	QuestionId           int64              `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerText           string             `protobuf:"bytes,2,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	VariantItems         []int32            `protobuf:"varint,3,rep,packed,name=variant_items,json=variantItems,proto3" json:"variant_items,omitempty"`
	FreeText             []*AnswersFreeText `protobuf:"bytes,4,rep,name=free_text,json=freeText,proto3" json:"free_text,omitempty"`
	SpentTime            int32              `protobuf:"varint,5,opt,name=spent_time,json=spentTime,proto3" json:"spent_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PAYLOAD) Reset()         { *m = PAYLOAD{} }
func (m *PAYLOAD) String() string { return proto.CompactTextString(m) }
func (*PAYLOAD) ProtoMessage()    {}
func (*PAYLOAD) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{10}
}

func (m *PAYLOAD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PAYLOAD.Unmarshal(m, b)
}
func (m *PAYLOAD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PAYLOAD.Marshal(b, m, deterministic)
}
func (m *PAYLOAD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PAYLOAD.Merge(m, src)
}
func (m *PAYLOAD) XXX_Size() int {
	return xxx_messageInfo_PAYLOAD.Size(m)
}
func (m *PAYLOAD) XXX_DiscardUnknown() {
	xxx_messageInfo_PAYLOAD.DiscardUnknown(m)
}

var xxx_messageInfo_PAYLOAD proto.InternalMessageInfo

func (m *PAYLOAD) GetQuestionId() int64 {
	if m != nil {
		return m.QuestionId
	}
	return 0
}

func (m *PAYLOAD) GetAnswerText() string {
	if m != nil {
		return m.AnswerText
	}
	return ""
}

func (m *PAYLOAD) GetVariantItems() []int32 {
	if m != nil {
		return m.VariantItems
	}
	return nil
}

func (m *PAYLOAD) GetFreeText() []*AnswersFreeText {
	if m != nil {
		return m.FreeText
	}
	return nil
}

func (m *PAYLOAD) GetSpentTime() int32 {
	if m != nil {
		return m.SpentTime
	}
	return 0
}

type AnswersFreeText struct {
	AnswerId             int32    `protobuf:"varint,1,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	AnswerText           string   `protobuf:"bytes,2,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswersFreeText) Reset()         { *m = AnswersFreeText{} }
func (m *AnswersFreeText) String() string { return proto.CompactTextString(m) }
func (*AnswersFreeText) ProtoMessage()    {}
func (*AnswersFreeText) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{11}
}

func (m *AnswersFreeText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswersFreeText.Unmarshal(m, b)
}
func (m *AnswersFreeText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswersFreeText.Marshal(b, m, deterministic)
}
func (m *AnswersFreeText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswersFreeText.Merge(m, src)
}
func (m *AnswersFreeText) XXX_Size() int {
	return xxx_messageInfo_AnswersFreeText.Size(m)
}
func (m *AnswersFreeText) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswersFreeText.DiscardUnknown(m)
}

var xxx_messageInfo_AnswersFreeText proto.InternalMessageInfo

func (m *AnswersFreeText) GetAnswerId() int32 {
	if m != nil {
		return m.AnswerId
	}
	return 0
}

func (m *AnswersFreeText) GetAnswerText() string {
	if m != nil {
		return m.AnswerText
	}
	return ""
}

type ANSWER struct {
	Longitude            float64    `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64    `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Uid                  string     `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Answers              []*PAYLOAD `protobuf:"bytes,4,rep,name=answers,proto3" json:"answers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ANSWER) Reset()         { *m = ANSWER{} }
func (m *ANSWER) String() string { return proto.CompactTextString(m) }
func (*ANSWER) ProtoMessage()    {}
func (*ANSWER) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{12}
}

func (m *ANSWER) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ANSWER.Unmarshal(m, b)
}
func (m *ANSWER) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ANSWER.Marshal(b, m, deterministic)
}
func (m *ANSWER) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ANSWER.Merge(m, src)
}
func (m *ANSWER) XXX_Size() int {
	return xxx_messageInfo_ANSWER.Size(m)
}
func (m *ANSWER) XXX_DiscardUnknown() {
	xxx_messageInfo_ANSWER.DiscardUnknown(m)
}

var xxx_messageInfo_ANSWER proto.InternalMessageInfo

func (m *ANSWER) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *ANSWER) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *ANSWER) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ANSWER) GetAnswers() []*PAYLOAD {
	if m != nil {
		return m.Answers
	}
	return nil
}

type Block struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Prevblockhash        []byte   `protobuf:"bytes,2,opt,name=prevblockhash,proto3" json:"prevblockhash,omitempty"`
	Data                 *ANSWER  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Hash                 []byte   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{13}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetPrevblockhash() []byte {
	if m != nil {
		return m.Prevblockhash
	}
	return nil
}

func (m *Block) GetData() *ANSWER {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Nothing struct {
	Dummy                bool     `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{14}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

func (m *Nothing) GetDummy() bool {
	if m != nil {
		return m.Dummy
	}
	return false
}

type Storage struct {
	Start                int64       `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Side                 StorageSide `protobuf:"varint,2,opt,name=Side,proto3,enum=manage.StorageSide" json:"Side,omitempty"`
	Type                 string      `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	PollId               int64       `protobuf:"varint,4,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Uid                  string      `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Data                 []byte      `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Storage) Reset()         { *m = Storage{} }
func (m *Storage) String() string { return proto.CompactTextString(m) }
func (*Storage) ProtoMessage()    {}
func (*Storage) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{15}
}

func (m *Storage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Storage.Unmarshal(m, b)
}
func (m *Storage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Storage.Marshal(b, m, deterministic)
}
func (m *Storage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Storage.Merge(m, src)
}
func (m *Storage) XXX_Size() int {
	return xxx_messageInfo_Storage.Size(m)
}
func (m *Storage) XXX_DiscardUnknown() {
	xxx_messageInfo_Storage.DiscardUnknown(m)
}

var xxx_messageInfo_Storage proto.InternalMessageInfo

func (m *Storage) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Storage) GetSide() StorageSide {
	if m != nil {
		return m.Side
	}
	return Storage_IN
}

func (m *Storage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Storage) GetPollId() int64 {
	if m != nil {
		return m.PollId
	}
	return 0
}

func (m *Storage) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Storage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ServiceInformation struct {
	ArrNodes             []string `protobuf:"bytes,1,rep,name=ArrNodes,proto3" json:"ArrNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInformation) Reset()         { *m = ServiceInformation{} }
func (m *ServiceInformation) String() string { return proto.CompactTextString(m) }
func (*ServiceInformation) ProtoMessage()    {}
func (*ServiceInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{16}
}

func (m *ServiceInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInformation.Unmarshal(m, b)
}
func (m *ServiceInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInformation.Marshal(b, m, deterministic)
}
func (m *ServiceInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInformation.Merge(m, src)
}
func (m *ServiceInformation) XXX_Size() int {
	return xxx_messageInfo_ServiceInformation.Size(m)
}
func (m *ServiceInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInformation.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInformation proto.InternalMessageInfo

func (m *ServiceInformation) GetArrNodes() []string {
	if m != nil {
		return m.ArrNodes
	}
	return nil
}

type RequestAPI struct {
	Query                TypeQuery `protobuf:"varint,1,opt,name=Query,proto3,enum=manage.TypeQuery" json:"Query,omitempty"`
	IdPoll               int64     `protobuf:"varint,2,opt,name=IdPoll,proto3" json:"IdPoll,omitempty"`
	Params               []byte    `protobuf:"bytes,3,opt,name=Params,proto3" json:"Params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RequestAPI) Reset()         { *m = RequestAPI{} }
func (m *RequestAPI) String() string { return proto.CompactTextString(m) }
func (*RequestAPI) ProtoMessage()    {}
func (*RequestAPI) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{17}
}

func (m *RequestAPI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAPI.Unmarshal(m, b)
}
func (m *RequestAPI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAPI.Marshal(b, m, deterministic)
}
func (m *RequestAPI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAPI.Merge(m, src)
}
func (m *RequestAPI) XXX_Size() int {
	return xxx_messageInfo_RequestAPI.Size(m)
}
func (m *RequestAPI) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAPI.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAPI proto.InternalMessageInfo

func (m *RequestAPI) GetQuery() TypeQuery {
	if m != nil {
		return m.Query
	}
	return TypeQuery_DETAIL
}

func (m *RequestAPI) GetIdPoll() int64 {
	if m != nil {
		return m.IdPoll
	}
	return 0
}

func (m *RequestAPI) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

type ResponseAPI struct {
	LastChange           int64     `protobuf:"varint,1,opt,name=LastChange,proto3" json:"LastChange,omitempty"`
	Query                TypeQuery `protobuf:"varint,2,opt,name=Query,proto3,enum=manage.TypeQuery" json:"Query,omitempty"`
	Data                 []byte    `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Session              uint64    `protobuf:"varint,4,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseAPI) Reset()         { *m = ResponseAPI{} }
func (m *ResponseAPI) String() string { return proto.CompactTextString(m) }
func (*ResponseAPI) ProtoMessage()    {}
func (*ResponseAPI) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{18}
}

func (m *ResponseAPI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseAPI.Unmarshal(m, b)
}
func (m *ResponseAPI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseAPI.Marshal(b, m, deterministic)
}
func (m *ResponseAPI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseAPI.Merge(m, src)
}
func (m *ResponseAPI) XXX_Size() int {
	return xxx_messageInfo_ResponseAPI.Size(m)
}
func (m *ResponseAPI) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseAPI.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseAPI proto.InternalMessageInfo

func (m *ResponseAPI) GetLastChange() int64 {
	if m != nil {
		return m.LastChange
	}
	return 0
}

func (m *ResponseAPI) GetQuery() TypeQuery {
	if m != nil {
		return m.Query
	}
	return TypeQuery_DETAIL
}

func (m *ResponseAPI) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseAPI) GetSession() uint64 {
	if m != nil {
		return m.Session
	}
	return 0
}

type TypeServer struct {
	UserAgent            string         `protobuf:"bytes,1,opt,name=UserAgent,proto3" json:"UserAgent,omitempty"`
	Side                 TypeServerSide `protobuf:"varint,2,opt,name=Side,proto3,enum=manage.TypeServerSide" json:"Side,omitempty"`
	Type                 string         `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	PollId               int64          `protobuf:"varint,4,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Data                 []byte         `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TypeServer) Reset()         { *m = TypeServer{} }
func (m *TypeServer) String() string { return proto.CompactTextString(m) }
func (*TypeServer) ProtoMessage()    {}
func (*TypeServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_519fa8ed5ffbbc8f, []int{19}
}

func (m *TypeServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeServer.Unmarshal(m, b)
}
func (m *TypeServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeServer.Marshal(b, m, deterministic)
}
func (m *TypeServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeServer.Merge(m, src)
}
func (m *TypeServer) XXX_Size() int {
	return xxx_messageInfo_TypeServer.Size(m)
}
func (m *TypeServer) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeServer.DiscardUnknown(m)
}

var xxx_messageInfo_TypeServer proto.InternalMessageInfo

func (m *TypeServer) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *TypeServer) GetSide() TypeServerSide {
	if m != nil {
		return m.Side
	}
	return TypeServer_IN
}

func (m *TypeServer) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TypeServer) GetPollId() int64 {
	if m != nil {
		return m.PollId
	}
	return 0
}

func (m *TypeServer) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("manage.TypeQuery", TypeQuery_name, TypeQuery_value)
	proto.RegisterEnum("manage.ResponseWideType", ResponseWideType_name, ResponseWideType_value)
	proto.RegisterEnum("manage.StorageSide", StorageSide_name, StorageSide_value)
	proto.RegisterEnum("manage.TypeServerSide", TypeServerSide_name, TypeServerSide_value)
	proto.RegisterType((*Request)(nil), "manage.Request")
	proto.RegisterType((*Response)(nil), "manage.Response")
	proto.RegisterType((*EXTRA)(nil), "manage.EXTRA")
	proto.RegisterType((*ResponseWide)(nil), "manage.ResponseWide")
	proto.RegisterType((*COUNTS_VARIANT)(nil), "manage.COUNTS_VARIANT")
	proto.RegisterType((*TEXTS_VARIANT)(nil), "manage.TEXTS_VARIANT")
	proto.RegisterType((*SummaryAnswersCounts)(nil), "manage.SummaryAnswersCounts")
	proto.RegisterType((*SummaryAnswersTexts)(nil), "manage.SummaryAnswersTexts")
	proto.RegisterType((*VARIANTS)(nil), "manage.VARIANTS")
	proto.RegisterType((*Items)(nil), "manage.Items")
	proto.RegisterType((*PAYLOAD)(nil), "manage.PAYLOAD")
	proto.RegisterType((*AnswersFreeText)(nil), "manage.AnswersFreeText")
	proto.RegisterType((*ANSWER)(nil), "manage.ANSWER")
	proto.RegisterType((*Block)(nil), "manage.Block")
	proto.RegisterType((*Nothing)(nil), "manage.Nothing")
	proto.RegisterType((*Storage)(nil), "manage.Storage")
	proto.RegisterType((*ServiceInformation)(nil), "manage.ServiceInformation")
	proto.RegisterType((*RequestAPI)(nil), "manage.RequestAPI")
	proto.RegisterType((*ResponseAPI)(nil), "manage.ResponseAPI")
	proto.RegisterType((*TypeServer)(nil), "manage.TypeServer")
}

func init() { proto.RegisterFile("manage.proto", fileDescriptor_519fa8ed5ffbbc8f) }

var fileDescriptor_519fa8ed5ffbbc8f = []byte{
	// 1113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x72, 0xe3, 0x34,
	0x14, 0x8e, 0xed, 0x38, 0x3f, 0x27, 0xfd, 0xf1, 0x6a, 0x4b, 0x1b, 0xca, 0xcf, 0x76, 0x04, 0x03,
	0x5d, 0x18, 0x4a, 0xc9, 0xee, 0xc2, 0x0d, 0x37, 0xa6, 0x4d, 0xbb, 0x66, 0xdb, 0x34, 0x28, 0x2e,
	0xdd, 0x5e, 0x65, 0xbc, 0xb5, 0x36, 0xf5, 0x10, 0xdb, 0xc1, 0x56, 0x4a, 0xcb, 0x0d, 0x17, 0xf0,
	0x36, 0x5c, 0xc1, 0x0c, 0xc3, 0x13, 0xf0, 0x5e, 0xcc, 0x91, 0xe5, 0x38, 0x49, 0x33, 0xdd, 0xc2,
	0x9d, 0xce, 0xd1, 0x91, 0xce, 0xf7, 0x7d, 0x3a, 0x3a, 0x12, 0x2c, 0x85, 0x5e, 0xe4, 0x0d, 0xf8,
	0xce, 0x28, 0x89, 0x45, 0x4c, 0x2a, 0x99, 0x45, 0x3f, 0x87, 0x2a, 0xe3, 0x3f, 0x8e, 0x79, 0x2a,
	0x88, 0x05, 0xc6, 0x0b, 0x7e, 0xd3, 0xd4, 0xb6, 0xb4, 0xed, 0x65, 0x86, 0x43, 0x42, 0xa0, 0xbc,
	0xef, 0x09, 0xaf, 0xa9, 0x6f, 0x69, 0xdb, 0x4b, 0x4c, 0x8e, 0xe9, 0x2e, 0xd4, 0x18, 0x4f, 0x47,
	0x71, 0x94, 0xf2, 0x7b, 0xae, 0x38, 0x00, 0xb3, 0xfd, 0xd2, 0x65, 0x36, 0x4e, 0x8a, 0x9b, 0x11,
	0x97, 0xf1, 0x75, 0x26, 0xc7, 0x64, 0x03, 0xaa, 0xa3, 0x78, 0x38, 0xec, 0x07, 0xbe, 0x5c, 0x63,
	0xb0, 0x0a, 0x9a, 0x8e, 0x8f, 0x7b, 0x8f, 0x03, 0xbf, 0x69, 0xc8, 0x58, 0x1c, 0xd2, 0x3f, 0x35,
	0x58, 0xca, 0x53, 0x9f, 0x05, 0x3e, 0x27, 0x9f, 0x41, 0xd9, 0xcd, 0xf7, 0x5b, 0x69, 0xbd, 0xbd,
	0xa3, 0x08, 0x4e, 0xc7, 0xec, 0x60, 0x12, 0x26, 0xc3, 0x72, 0xb4, 0x7a, 0x81, 0x76, 0x1d, 0x2a,
	0x8e, 0xdf, 0x8d, 0x87, 0x43, 0x99, 0xc6, 0x60, 0xca, 0x9a, 0xb0, 0x28, 0x4f, 0xb1, 0x78, 0x96,
	0x81, 0x27, 0x75, 0x30, 0xdb, 0xc7, 0x5d, 0xf7, 0xdc, 0x2a, 0x11, 0x80, 0xca, 0x81, 0xd3, 0x71,
	0x7a, 0xcf, 0x2d, 0x0d, 0xc7, 0x7b, 0xac, 0x6d, 0xbb, 0x6d, 0x4b, 0xc7, 0xb1, 0xdd, 0xe9, 0x9d,
	0xb5, 0x99, 0x65, 0xd0, 0x6f, 0x61, 0x65, 0xef, 0xe4, 0xb4, 0xe3, 0xf6, 0xfa, 0xdf, 0xdb, 0xcc,
	0xb1, 0x3b, 0x2e, 0x59, 0x01, 0x3d, 0xf0, 0x25, 0x66, 0x83, 0xe9, 0x81, 0x4f, 0xd6, 0xc0, 0xbc,
	0x88, 0xc7, 0x91, 0x90, 0xc0, 0x4c, 0x96, 0x19, 0x08, 0xe1, 0x75, 0xc2, 0xb9, 0x04, 0x56, 0x63,
	0x72, 0x4c, 0x0f, 0x61, 0xd9, 0x6d, 0xbf, 0xbc, 0x63, 0x2b, 0x02, 0xe5, 0x4b, 0x2f, 0xbd, 0x6c,
	0xea, 0x5b, 0x06, 0xe2, 0xc6, 0xb1, 0x14, 0x9d, 0x5f, 0x8b, 0xa6, 0xb1, 0x65, 0x48, 0xd1, 0xf9,
	0xb5, 0xa0, 0xc7, 0xb0, 0xd6, 0x1b, 0x87, 0xa1, 0x97, 0xdc, 0xd8, 0x51, 0xfa, 0x13, 0x4f, 0xd2,
	0x3d, 0xcc, 0x99, 0x92, 0x67, 0x00, 0x5e, 0xe6, 0xe8, 0xcb, 0x7d, 0x8d, 0xed, 0x46, 0x6b, 0x3d,
	0x97, 0x75, 0x96, 0x06, 0xab, 0xab, 0x48, 0xc7, 0xa7, 0x57, 0xf0, 0x70, 0x76, 0x3b, 0x97, 0x5f,
	0x8b, 0x94, 0x3c, 0x06, 0x4b, 0xc5, 0x60, 0xd2, 0xbe, 0x44, 0xa6, 0x49, 0x64, 0xab, 0x53, 0xfe,
	0xe7, 0x08, 0xf2, 0xe9, 0x4c, 0x62, 0x5d, 0x26, 0x7e, 0x2b, 0x4f, 0x3c, 0xc3, 0x79, 0x3a, 0xef,
	0xdf, 0x1a, 0xd4, 0x94, 0xbb, 0x47, 0x1e, 0x41, 0x43, 0x96, 0x71, 0x10, 0x47, 0xfd, 0x89, 0x28,
	0x90, 0xbb, 0x1c, 0x7f, 0x8e, 0x9c, 0x7e, 0x4f, 0x72, 0xb8, 0x6f, 0x66, 0xf4, 0xa7, 0x64, 0x54,
	0x3b, 0x21, 0x4f, 0xd2, 0x82, 0x3a, 0x9e, 0x4e, 0x36, 0x5d, 0xbe, 0x0b, 0x7a, 0x0d, 0xe3, 0x70,
	0x0d, 0xfd, 0x19, 0x4c, 0x47, 0xf0, 0x30, 0xfd, 0x6f, 0x57, 0xe2, 0x23, 0x30, 0x03, 0x5c, 0x25,
	0x41, 0x34, 0x5a, 0x56, 0x9e, 0x25, 0xd7, 0x80, 0x65, 0xd3, 0xe4, 0x5d, 0xa8, 0x0f, 0x83, 0x30,
	0x10, 0x57, 0xb1, 0xe0, 0xb2, 0x86, 0x4d, 0x56, 0x38, 0xe8, 0x3f, 0x1a, 0x54, 0xbb, 0xf6, 0xf9,
	0xd1, 0x89, 0xbd, 0xff, 0x66, 0xd1, 0xe6, 0xd8, 0xeb, 0x12, 0xe6, 0x34, 0xfb, 0x0f, 0x60, 0xf9,
	0xca, 0x4b, 0x02, 0x2f, 0x12, 0xfd, 0x02, 0x9b, 0xc9, 0x96, 0x94, 0x33, 0x63, 0xf9, 0xf4, 0xb6,
	0x44, 0x1b, 0x39, 0x78, 0x55, 0x32, 0x07, 0x4a, 0x9a, 0x42, 0x24, 0xf2, 0x1e, 0x40, 0x3a, 0xe2,
	0x91, 0xe8, 0x8b, 0x20, 0xe4, 0x4d, 0x33, 0xe3, 0x21, 0x3d, 0x6e, 0x10, 0x72, 0x7a, 0x02, 0xab,
	0x73, 0x6b, 0xc9, 0x3b, 0xa0, 0x0e, 0x2e, 0x27, 0x63, 0xb2, 0x5a, 0xe6, 0xb8, 0x07, 0x15, 0xfa,
	0x4b, 0x7e, 0x6d, 0xa5, 0x80, 0x71, 0x34, 0x08, 0xc4, 0xd8, 0xcf, 0x8e, 0x46, 0x63, 0x85, 0x83,
	0x6c, 0x42, 0x6d, 0xe8, 0x89, 0x6c, 0x52, 0x97, 0x93, 0x13, 0xfb, 0x76, 0xd7, 0x22, 0x8f, 0xa1,
	0xaa, 0x8a, 0x49, 0x31, 0x5f, 0xcd, 0x99, 0xab, 0x43, 0x60, 0xf9, 0x3c, 0xfd, 0x55, 0x03, 0xf3,
	0x9b, 0x61, 0x7c, 0xf1, 0x03, 0x02, 0x40, 0xd2, 0xa9, 0xf0, 0xc2, 0x91, 0x3a, 0x95, 0xc2, 0x41,
	0x3e, 0x84, 0xe5, 0x51, 0xc2, 0xaf, 0x5e, 0x61, 0xa8, 0xba, 0xef, 0xd8, 0xa7, 0x66, 0x9d, 0x84,
	0x42, 0xd9, 0xc7, 0x26, 0x86, 0x58, 0x1a, 0xad, 0x95, 0x89, 0xde, 0x92, 0x22, 0x93, 0x73, 0x93,
	0x86, 0xa1, 0x1a, 0x1d, 0x8e, 0xe9, 0x23, 0xa8, 0x76, 0x62, 0x71, 0x19, 0x44, 0x03, 0x6c, 0x4d,
	0xfe, 0x38, 0x0c, 0xb3, 0x0e, 0x5f, 0x63, 0x99, 0x41, 0xff, 0xd2, 0xa0, 0xda, 0x13, 0x71, 0xe2,
	0x0d, 0x38, 0x46, 0xa4, 0xc2, 0x4b, 0x84, 0x02, 0x99, 0x19, 0x64, 0x1b, 0xca, 0xbd, 0x40, 0xa9,
	0xb3, 0xd2, 0x5a, 0xcb, 0x53, 0xab, 0x45, 0x3b, 0x69, 0xe0, 0x73, 0x26, 0x23, 0x26, 0xf5, 0x6f,
	0x2c, 0xae, 0xff, 0xf2, 0xa2, 0x27, 0xc1, 0x2c, 0xc4, 0xcd, 0x1b, 0x75, 0x65, 0xaa, 0x51, 0x6f,
	0x40, 0x19, 0x13, 0x90, 0x0a, 0xe8, 0x4e, 0xc7, 0x2a, 0x91, 0x2a, 0x18, 0x27, 0xa7, 0xae, 0xa5,
	0xd1, 0x5d, 0x20, 0x3d, 0x9e, 0x5c, 0x05, 0x17, 0xdc, 0x89, 0x5e, 0xc7, 0x49, 0xe8, 0x61, 0x8d,
	0xe3, 0x69, 0xda, 0x49, 0xd2, 0x89, 0x7d, 0x9e, 0xca, 0xee, 0x54, 0x67, 0x13, 0x9b, 0x72, 0x00,
	0xf5, 0x38, 0xda, 0x5d, 0x87, 0x7c, 0x0c, 0xe6, 0x77, 0x63, 0x9e, 0xdc, 0xa8, 0xf7, 0xe6, 0xc1,
	0xe4, 0x92, 0xdf, 0x8c, 0xb8, 0x9c, 0x60, 0xd9, 0xfc, 0xd4, 0xb3, 0xa2, 0xcf, 0x3c, 0x2b, 0xeb,
	0x50, 0xe9, 0x7a, 0x89, 0x27, 0x2f, 0x09, 0xe2, 0x55, 0x16, 0xfd, 0x4d, 0x83, 0x46, 0xfe, 0x68,
	0x61, 0xa2, 0xf7, 0x01, 0x8e, 0xbc, 0x54, 0xec, 0x5d, 0x7a, 0xd1, 0x80, 0xe7, 0x97, 0xb2, 0xf0,
	0x14, 0x40, 0xf4, 0x37, 0x00, 0xc9, 0xe5, 0x31, 0x0a, 0x79, 0x48, 0x13, 0xaa, 0x29, 0x4f, 0xd3,
	0x20, 0x8e, 0xa4, 0xba, 0x65, 0x96, 0x9b, 0xf4, 0x0f, 0x0d, 0x00, 0xb7, 0x40, 0x91, 0x78, 0x82,
	0x35, 0x78, 0x9a, 0xf2, 0xc4, 0x1e, 0xf0, 0x48, 0xa8, 0xfe, 0x54, 0x38, 0xc8, 0xa7, 0x33, 0x47,
	0xbc, 0x31, 0x0d, 0x21, 0x5b, 0xff, 0xbf, 0x4f, 0x99, 0xa8, 0xba, 0x35, 0x33, 0xd0, 0xfe, 0x5d,
	0x67, 0xfa, 0xc9, 0x17, 0x50, 0x9f, 0xb0, 0xc6, 0x77, 0x77, 0xbf, 0xed, 0xda, 0xce, 0x91, 0x55,
	0x22, 0x0d, 0xa8, 0xf6, 0x4e, 0x8f, 0x8f, 0x6d, 0x76, 0x6e, 0x69, 0x68, 0x9c, 0x76, 0x5e, 0x74,
	0x4e, 0xce, 0x3a, 0x96, 0xde, 0xfa, 0x5d, 0x87, 0x07, 0xc7, 0x12, 0x2d, 0xea, 0xa1, 0x2a, 0x82,
	0x7c, 0x09, 0xcb, 0x87, 0x5c, 0x4c, 0xd1, 0x9f, 0x5c, 0x53, 0x75, 0x19, 0x36, 0xc9, 0x6d, 0x8e,
	0xb4, 0x44, 0x9e, 0x40, 0xad, 0xc7, 0x23, 0x5f, 0x4a, 0xbb, 0x5a, 0xfc, 0x40, 0x64, 0xd1, 0x6c,
	0x5a, 0xf3, 0x5f, 0x12, 0x5a, 0xda, 0xd6, 0x76, 0x35, 0xd2, 0x82, 0xea, 0x21, 0x17, 0x8b, 0xd7,
	0xac, 0x2d, 0xfa, 0xc6, 0xd0, 0x12, 0xf9, 0x1a, 0x1a, 0x79, 0x22, 0xac, 0x91, 0x87, 0xf3, 0x61,
	0x76, 0xd7, 0x29, 0x20, 0x16, 0x55, 0xab, 0x32, 0x7e, 0x05, 0xa0, 0x32, 0xe2, 0xe2, 0x05, 0x71,
	0x9b, 0x8b, 0x36, 0xa4, 0xa5, 0x57, 0x15, 0xf9, 0x5d, 0x7c, 0xf2, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x0a, 0x18, 0x95, 0x03, 0x3e, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManageDataServiceClient is the client API for ManageDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManageDataServiceClient interface {
	GetTypeServer(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*TypeServer, error)
	SendData(ctx context.Context, opts ...grpc.CallOption) (ManageDataService_SendDataClient, error)
	GetData(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseWide, error)
	SendDataAPI(ctx context.Context, opts ...grpc.CallOption) (ManageDataService_SendDataAPIClient, error)
	GetDataAPI(ctx context.Context, in *RequestAPI, opts ...grpc.CallOption) (*ResponseAPI, error)
}

type manageDataServiceClient struct {
	cc *grpc.ClientConn
}

func NewManageDataServiceClient(cc *grpc.ClientConn) ManageDataServiceClient {
	return &manageDataServiceClient{cc}
}

func (c *manageDataServiceClient) GetTypeServer(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*TypeServer, error) {
	out := new(TypeServer)
	err := c.cc.Invoke(ctx, "/manage.ManageDataService/GetTypeServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manageDataServiceClient) SendData(ctx context.Context, opts ...grpc.CallOption) (ManageDataService_SendDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ManageDataService_serviceDesc.Streams[0], "/manage.ManageDataService/SendData", opts...)
	if err != nil {
		return nil, err
	}
	x := &manageDataServiceSendDataClient{stream}
	return x, nil
}

type ManageDataService_SendDataClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type manageDataServiceSendDataClient struct {
	grpc.ClientStream
}

func (x *manageDataServiceSendDataClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *manageDataServiceSendDataClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *manageDataServiceClient) GetData(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseWide, error) {
	out := new(ResponseWide)
	err := c.cc.Invoke(ctx, "/manage.ManageDataService/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manageDataServiceClient) SendDataAPI(ctx context.Context, opts ...grpc.CallOption) (ManageDataService_SendDataAPIClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ManageDataService_serviceDesc.Streams[1], "/manage.ManageDataService/SendDataAPI", opts...)
	if err != nil {
		return nil, err
	}
	x := &manageDataServiceSendDataAPIClient{stream}
	return x, nil
}

type ManageDataService_SendDataAPIClient interface {
	Send(*ResponseAPI) error
	Recv() (*RequestAPI, error)
	grpc.ClientStream
}

type manageDataServiceSendDataAPIClient struct {
	grpc.ClientStream
}

func (x *manageDataServiceSendDataAPIClient) Send(m *ResponseAPI) error {
	return x.ClientStream.SendMsg(m)
}

func (x *manageDataServiceSendDataAPIClient) Recv() (*RequestAPI, error) {
	m := new(RequestAPI)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *manageDataServiceClient) GetDataAPI(ctx context.Context, in *RequestAPI, opts ...grpc.CallOption) (*ResponseAPI, error) {
	out := new(ResponseAPI)
	err := c.cc.Invoke(ctx, "/manage.ManageDataService/GetDataAPI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManageDataServiceServer is the server API for ManageDataService service.
type ManageDataServiceServer interface {
	GetTypeServer(context.Context, *Nothing) (*TypeServer, error)
	SendData(ManageDataService_SendDataServer) error
	GetData(context.Context, *Request) (*ResponseWide, error)
	SendDataAPI(ManageDataService_SendDataAPIServer) error
	GetDataAPI(context.Context, *RequestAPI) (*ResponseAPI, error)
}

func RegisterManageDataServiceServer(s *grpc.Server, srv ManageDataServiceServer) {
	s.RegisterService(&_ManageDataService_serviceDesc, srv)
}

func _ManageDataService_GetTypeServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManageDataServiceServer).GetTypeServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manage.ManageDataService/GetTypeServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManageDataServiceServer).GetTypeServer(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManageDataService_SendData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ManageDataServiceServer).SendData(&manageDataServiceSendDataServer{stream})
}

type ManageDataService_SendDataServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type manageDataServiceSendDataServer struct {
	grpc.ServerStream
}

func (x *manageDataServiceSendDataServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *manageDataServiceSendDataServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ManageDataService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManageDataServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manage.ManageDataService/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManageDataServiceServer).GetData(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManageDataService_SendDataAPI_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ManageDataServiceServer).SendDataAPI(&manageDataServiceSendDataAPIServer{stream})
}

type ManageDataService_SendDataAPIServer interface {
	Send(*RequestAPI) error
	Recv() (*ResponseAPI, error)
	grpc.ServerStream
}

type manageDataServiceSendDataAPIServer struct {
	grpc.ServerStream
}

func (x *manageDataServiceSendDataAPIServer) Send(m *RequestAPI) error {
	return x.ServerStream.SendMsg(m)
}

func (x *manageDataServiceSendDataAPIServer) Recv() (*ResponseAPI, error) {
	m := new(ResponseAPI)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ManageDataService_GetDataAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAPI)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManageDataServiceServer).GetDataAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manage.ManageDataService/GetDataAPI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManageDataServiceServer).GetDataAPI(ctx, req.(*RequestAPI))
	}
	return interceptor(ctx, in, info, handler)
}

var _ManageDataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "manage.ManageDataService",
	HandlerType: (*ManageDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTypeServer",
			Handler:    _ManageDataService_GetTypeServer_Handler,
		},
		{
			MethodName: "GetData",
			Handler:    _ManageDataService_GetData_Handler,
		},
		{
			MethodName: "GetDataAPI",
			Handler:    _ManageDataService_GetDataAPI_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendData",
			Handler:       _ManageDataService_SendData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendDataAPI",
			Handler:       _ManageDataService_SendDataAPI_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "manage.proto",
}
